 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pages;

import Controllers.PageController.SettingController;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author pongp
 */
public class Setting extends javax.swing.JPanel{
    private SettingController sc;
    /**
     * Creates new form Page1
     */
    public Setting() {
        initComponents();
    }

    public Setting(SettingController aThis) {
        this.sc = aThis;
        initComponents();
    }
    
    public JPanel getPanel() {
        return this.jPanel2;
    }

    public JButton getButAcc() {
        return ButAcc;
    }

    public void setButAcc(JButton ButAcc) {
        this.ButAcc = ButAcc;
    }

    public JButton getButDisName() {
        return ButDisName;
    }

    public void setButDisName(JButton ButDisName) {
        this.ButDisName = ButDisName;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ButDisName = new javax.swing.JButton();
        ButAcc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 656));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Setting");

        jPanel1.setBackground(new java.awt.Color(158, 165, 241));

        ButDisName.setBackground(new java.awt.Color(247, 247, 247));
        ButDisName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ButDisName.setText("DisName");
        ButDisName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButDisName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButDisNameActionPerformed(evt);
            }
        });

        ButAcc.setBackground(new java.awt.Color(158, 165, 241));
        ButAcc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ButAcc.setText("Account");
        ButAcc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAccActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButDisName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ButDisName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ButAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 280, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(977, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButDisNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButDisNameActionPerformed
        sc.changeRoute("SettingPageName");
    }//GEN-LAST:event_ButDisNameActionPerformed

    private void ButAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAccActionPerformed
        sc.changeRoute("SettingPageAccount");
    }//GEN-LAST:event_ButAccActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAcc;
    private javax.swing.JButton ButDisName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
